enum DELTO_2F_COIL
{
//    MOVING_AVERAGE_FILTER = 0,
    REVERSE_MODE = 1,
    GRASP = 2,
    TORQUE = 3,
    EEPROM_WRITE = 4,
};

enum DELTO_2F_HOLDING_REGISTERS
{
   RS485_BAUDRATE = 0,
    MODBUS_SLAVE_ID = 1,

    ETHERNET_IP_CLASS_A = 2,
    ETHERNET_IP_CLASS_B = 3,
    ETHERNET_IP_CLASS_C = 4,
    ETHERNET_IP_CLASS_D = 5,

    ETHERNET_SUBNET_MASK_A = 6,
    ETHERNET_SUBNET_MASK_B = 7,
    ETHERNET_SUBNET_MASK_C = 8,
    ETHERNET_SUBNET_MASK_D = 9,

    ETHERNET_GATEWAY_A = 10,
    ETHERNET_GATEWAY_B = 11,
    ETHERNET_GATEWAY_C = 12,
    ETHERNET_GATEWAY_D = 13,

    ETHERNET_PORT = 14,

    MOTOR_PGAIN = 15,
    MOTOR_DGAIN = 16,

    OPEN_POSITION = 18,
    CLOSE_POSITION = 19,
    LOW_FORCE = 20,
    HIGH_FORCE = 21,
 
};

enum  DELTO_2F_INPUT_REGISTERS
{
    PRODUCT_ID = 0,
    FIRMWARE_VERSION = 1,

    MOTOR_CURRENT_POSITION = 2,
    
    MOTOR_ELECTRIC_CURRENT = 3,
    MOTOR_ARRIVED_TARGET_POSITION = 4,
    MOTOR_ARRIVED_ELECTRIC_CURRENT = 5,
    
};
